.\" man page create by R# package system.
.TH MESH 1 2000-Jan "as.mzPack" "as.mzPack"
.SH NAME
as.mzPack \- 
.SH SYNOPSIS
\fIas.mzPack(\fBexpr1\fR as <generic> Matrix, 
\fBq\fR as double = 0.7, 
\fBrt_range\fR as any = [1,840], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
