.\" man page create by R# package system.
.TH MESH 1 2000-Jan "as.mzPack" "as.mzPack"
.SH NAME
as.mzPack \- Cast the data expression matrix as the mzkit mzpack object
.SH SYNOPSIS
\fIas.mzPack(\fBexpr1\fR as <generic> Matrix, 
\fBmesh\fR as <generic> MeshArguments = \fB<NULL>\fR, 
\fBq\fR as double = 0.7, 
\fBrt_range\fR as any = [1,840], 
\fBspatial\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Cast the data expression matrix as the mzkit mzpack object
.PP
.SH OPTIONS
.PP
\fBexpr1\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.PP
\fBrt_range\fB \fR\- -. 
.PP
.PP
\fBspatial\fB \fR\- Current expression matrix is a spatial matrix?. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
