.\" man page create by R# package system.
.TH MESH 1 2000-Jan "expr1" "expr1"
.SH NAME
expr1 \- Generate the metabolomics expression matrix object
.SH SYNOPSIS
\fIexpr1(\fBmesh\fR as <generic> MeshArguments, 
\fBmzpack\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Generate the metabolomics expression matrix object
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
