.\" man page create by R# package system.
.TH MESH 1 2000-Jan "featureSet" "featureSet"
.SH NAME
featureSet \- Get the ion feature set based on the configed mesh argument
.SH SYNOPSIS
\fIfeatureSet(\fBmesh\fR as <generic> MeshArguments);\fR
.SH DESCRIPTION
.PP
Get the ion feature set based on the configed mesh argument
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
