.\" man page create by R# package system.
.TH MESH 1 2000-Jan "formula" "formula"
.SH NAME
formula \- 
.SH SYNOPSIS
\fIformula(\fBmesh\fR as <generic> MeshArguments, 
\fBC\fR as any = [1,9], 
\fBH\fR as any = [0,60], 
\fBO\fR as any = [0,18], 
\fBN\fR as any = [0,10], 
\fBP\fR as any = [0,8], 
\fBS\fR as any = [0,8], 
\fBF\fR as any = [0,15], 
\fBCl\fR as any = [0,8], 
\fBBr\fR as any = [0,5], 
\fBSi\fR as any = [0,8]);\fR
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
