.\" man page create by R# package system.
.TH MESH 1 2000-Jan "mesh" "mesh"
.SH NAME
mesh \- Create a mesh argument for run metabolomics expression matrix simulation
.SH SYNOPSIS
\fImesh(\fBmass_range\fR as any = [50,1200], 
\fBfeatures\fR as any = 10000, 
\fBmzdiff\fR as double = 0.005, 
\fBadducts\fR as any = ["[M+H]+","[M+Na]+","[M+K]+","[M+NH4]+","[M+H2O+H]+","[M-H2O+H]+"], 
\fBintensity_max\fR as double = 100000, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a mesh argument for run metabolomics expression matrix simulation
.PP
.SH OPTIONS
.PP
\fBmass_range\fB \fR\- -. 
.PP
.PP
\fBfeatures\fB \fR\- 
 set the number of the ion features in the generated dataset, 
 andalso you could set the ion set manually from this 
 parameter.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
