.\" man page create by R# package system.
.TH MESH 1 2000-Jan "metabolites" "metabolites"
.SH NAME
metabolites \- 
.SH SYNOPSIS
\fImetabolites(\fBmesh\fR as <generic> MeshArguments, 
\fBmetabolites\fR as <generic> MetaboliteAnnotation[], 
\fBadducts\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
