.\" man page create by R# package system.
.TH MESH 1 2000-Jan "metabolites" "metabolites"
.SH NAME
metabolites \- Set metabolite features
.SH SYNOPSIS
\fImetabolites(\fBmesh\fR as <generic> MeshArguments, 
\fBmetabolites\fR as any, 
\fBadducts\fR as any = ["[M+H]+","[M+Na]+","[M+K]+","[M+NH4]+","[M+H2O+H]+","[M-H2O+H]+"], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set metabolite features
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.PP
\fBmetabolites\fB \fR\- 
 A collection of the metabolite annotation data model that contains 
 the basic annotation metadata: 
 
 1. id, 
 2. name, 
 3. exact mass, 
 4. and formula data
 
 this parameter value could be the annotation abstract model: @\fBT:BioNovoGene.BioDeep.Chemoinformatics.MetaboliteAnnotation\fR,
 or the kegg compound model @\fBT:SMRUCC.genomics.Assembly.KEGG.DBGET.bGetObject.Compound\fR from the GCModeller package.
. 
.PP
.PP
\fBadducts\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
