.\" man page create by R# package system.
.TH MESH 1 2000-Jan "samples.raster" "samples.raster"
.SH NAME
samples.raster \- 
.SH SYNOPSIS
\fIsamples.raster(\fBmesh\fR as <generic> MeshArguments, 
\fBraster\fR as <generic> RasterScaler, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
