.\" man page create by R# package system.
.TH MESH 1 2000-Jan "samples.spatial" "samples.spatial"
.SH NAME
samples.spatial \- Set spatial id
.SH SYNOPSIS
\fIsamples.spatial(\fBmesh\fR as <generic> MeshArguments, 
\fBx\fR as any, 
\fBy\fR as any, 
\fBz\fR as any = \fB<NULL>\fR, 
\fBkernel\fR as any = \fB<NULL>\fR, 
\fBgroup\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set spatial id
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBz\fB \fR\- 
 z axis of the spatial spot
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
