.\" man page create by R# package system.
.TH MESH 1 2000-Jan "sample.cal_spatial" "sample.cal_spatial"
.SH NAME
sample.cal_spatial \- 
.SH SYNOPSIS
\fIsample.cal_spatial(\fBmesh\fR as <generic> MeshArguments, 
\fBx\fR as any, 
\fBy\fR as any, 
\fBlevel\fR as double, 
\fBtemplate\fR as string = "[raster-%y.raw][Scan_%d][%x,%y] FTMS + p NSI Full ms [%min-%max]", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
