.\" man page create by R# package system.
.TH MESH 1 2000-Jan "samples.raster" "samples.raster"
.SH NAME
samples.raster \- Create a spatial sample via the given raster matrix
.SH SYNOPSIS
\fIsamples.raster(\fBmesh\fR as <generic> MeshArguments, 
\fBraster\fR as <generic> RasterScaler, 
\fBlabel\fR as any = \fB<NULL>\fR, 
\fBkernel_cutoff\fR as double = 1E-05, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a spatial sample via the given raster matrix
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.PP
\fBraster\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
