.\" man page create by R# package system.
.TH MESH 1 2000-Jan "samples" "samples"
.SH NAME
samples \- Set sample labels and group labels information
.SH SYNOPSIS
\fIsamples(\fBmesh\fR as <generic> MeshArguments, 
\fBsampleinfo\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set sample labels and group labels information
.PP
.SH OPTIONS
.PP
\fBmesh\fB \fR\- -. 
.PP
.PP
\fBsampleinfo\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
Mesh.dll
.PP
